"""some_text

Revision ID: 1838704fbb3e
Revises: 5a69415bf9e7
Create Date: 2024-06-18 11:20:04.684717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1838704fbb3e'
down_revision = '5a69415bf9e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('constructionStatus', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'constructionStatus')
    # ### end Alembic commands ###
