"""init

Revision ID: 27a29302f08b
Revises: 54693a3bbce3
Create Date: 2023-07-11 16:34:08.462835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a29302f08b'
down_revision = '54693a3bbce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buildingId', sa.Integer(), nullable=True),
    sa.Column('att_name', sa.String(), nullable=True),
    sa.Column('att_value', sa.String(), nullable=True),
    sa.Column('logoWhiteNoTextSvg', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buildingId'], ['building.buildingId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_attributes')
    # ### end Alembic commands ###
