"""01x

Revision ID: 2d5d2a34b896
Revises: 59aeddf9cd0b
Create Date: 2023-11-16 16:42:17.041347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5d2a34b896'
down_revision = '59aeddf9cd0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('minPrice', sa.Float(), nullable=True))
    op.add_column('building', sa.Column('minPriceSqmByLayouts', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'minPriceSqmByLayouts')
    op.drop_column('building', 'minPrice')
    # ### end Alembic commands ###
