"""init

Revision ID: 59aeddf9cd0b
Revises: 27a29302f08b
Create Date: 2023-07-11 16:34:37.784435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59aeddf9cd0b'
down_revision = '27a29302f08b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_attributes', 'logoWhiteNoTextSvg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_attributes', sa.Column('logoWhiteNoTextSvg', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
