"""some_text

Revision ID: 5a69415bf9e7
Revises: 2d5d2a34b896
Create Date: 2024-06-18 11:12:02.361406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a69415bf9e7'
down_revision = '2d5d2a34b896'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('subLocalityNominative', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'subLocalityNominative')
    # ### end Alembic commands ###
