"""some_text

Revision ID: a14e50f4f803
Revises: 61da35b2d6e2
Create Date: 2024-06-19 14:47:17.880600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14e50f4f803'
down_revision = '61da35b2d6e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
