"""init

Revision ID: baa875906414
Revises: ed4623be17d8
Create Date: 2023-07-11 15:02:19.475145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa875906414'
down_revision = 'ed4623be17d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('buildingId', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('minPriceSqm', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('salesStatus', sa.String(), nullable=True),
    sa.Column('hasTaxInclusion', sa.Boolean(), nullable=True),
    sa.Column('isDeveloperPhoneShown', sa.Boolean(), nullable=True),
    sa.Column('developerCallTracking', sa.Boolean(), nullable=True),
    sa.Column('realtyCount', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsAppPhone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('buildingId')
    )
    op.create_table('developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('developerId', sa.Integer(), nullable=True),
    sa.Column('isBranded', sa.Boolean(), nullable=True),
    sa.Column('hexColor', sa.String(), nullable=True),
    sa.Column('logoWhiteNoTextSvg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('developer')
    op.drop_table('building')
    # ### end Alembic commands ###
