"""init

Revision ID: ed4623be17d8
Revises: 
Create Date: 2023-07-10 16:19:49.523319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4623be17d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('ObjectGUID', sa.UUID(), nullable=False),
    sa.Column('ObjectName', sa.String(), nullable=True),
    sa.Column('FamilyGUID', sa.UUID(), nullable=True),
    sa.Column('FamilyName', sa.String(), nullable=True),
    sa.Column('CityGUID', sa.UUID(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('logoWeb', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('fotoWeb', sa.String(), nullable=True),
    sa.Column('DivisionName', sa.String(), nullable=True),
    sa.Column('DivisionGUID', sa.UUID(), nullable=True),
    sa.Column('ProjectName', sa.String(), nullable=True),
    sa.Column('ProjectGUID', sa.UUID(), nullable=True),
    sa.Column('ClassGUID', sa.UUID(), nullable=True),
    sa.Column('typeOfPlacement', sa.String(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('apartmentsArea', sa.Float(), nullable=True),
    sa.Column('entranceQuantity', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('group1', sa.Integer(), nullable=True),
    sa.Column('startSaleDate', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('launchDate', sa.String(), nullable=True),
    sa.Column('durationMonth', sa.Integer(), nullable=True),
    sa.Column('startDateSMR', sa.String(), nullable=True),
    sa.Column('smrDeadlinePlan', sa.String(), nullable=True),
    sa.Column('smrDeadlineFact', sa.String(), nullable=True),
    sa.Column('stateCommission', sa.String(), nullable=True),
    sa.Column('enterDateOperation', sa.String(), nullable=True),
    sa.Column('keyHandover', sa.Boolean(), nullable=True),
    sa.Column('docDate', sa.String(), nullable=True),
    sa.Column('dateDDU', sa.String(), nullable=True),
    sa.Column('picApartmentSheets', sa.String(), nullable=True),
    sa.Column('picOfficeSheets', sa.String(), nullable=True),
    sa.Column('picStorageSheets', sa.String(), nullable=True),
    sa.Column('heightOfWall', sa.String(), nullable=True),
    sa.Column('outdoorWall', sa.String(), nullable=True),
    sa.Column('warmingOutdoorWall', sa.String(), nullable=True),
    sa.Column('window', sa.String(), nullable=True),
    sa.Column('balcony', sa.String(), nullable=True),
    sa.Column('finishWall', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('facingMateriaOftheFacadeOfApartments', sa.String(), nullable=True),
    sa.Column('heatingType', sa.String(), nullable=True),
    sa.Column('heatingAppliances', sa.String(), nullable=True),
    sa.Column('ventBoxe', sa.String(), nullable=True),
    sa.Column('vent', sa.String(), nullable=True),
    sa.Column('smartHome', sa.Boolean(), nullable=True),
    sa.Column('lift', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('CountryGUID', sa.UUID(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ObjectGUID')
    )
    op.create_table('pomeshcheniye',
    sa.Column('PomeshcheniyeGUID', sa.UUID(), nullable=False),
    sa.Column('Pomeshcheniye', sa.String(), nullable=True),
    sa.Column('ObjectName', sa.String(), nullable=True),
    sa.Column('PomeshcheniyeType', sa.String(), nullable=True),
    sa.Column('Podezd', sa.Integer(), nullable=True),
    sa.Column('Etazh', sa.Integer(), nullable=True),
    sa.Column('RoomsCount', sa.Integer(), nullable=True),
    sa.Column('ChistovayaOtdelka', sa.Boolean(), nullable=True),
    sa.Column('Orient', sa.String(), nullable=True),
    sa.Column('Likvidnost', sa.String(), nullable=True),
    sa.Column('Potolki', sa.String(), nullable=True),
    sa.Column('Moshnost', sa.String(), nullable=True),
    sa.Column('deletionMark', sa.Boolean(), nullable=True),
    sa.Column('PloshadVnutrenaya', sa.Integer(), nullable=True),
    sa.Column('PloshadBalkonov', sa.Integer(), nullable=True),
    sa.Column('Balcony', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ObjectGUID', sa.UUID(), nullable=True),
    sa.Column('PomeshcheniyeTypeGUID', sa.UUID(), nullable=True),
    sa.Column('LikvidnostGUID', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('PomeshcheniyeGUID')
    )
    op.create_table('pomeshcheniye_full',
    sa.Column('PomeshcheniyeGUID', sa.UUID(), nullable=False),
    sa.Column('Pomeshcheniye', sa.String(), nullable=True),
    sa.Column('ObjectGUID', sa.UUID(), nullable=True),
    sa.Column('ObjectName', sa.String(), nullable=True),
    sa.Column('Data', sa.DateTime(), nullable=True),
    sa.Column('TypeId', sa.UUID(), nullable=True),
    sa.Column('Price', sa.BIGINT(), nullable=True),
    sa.Column('Etazh', sa.Integer(), nullable=True),
    sa.Column('FirstPrice', sa.Integer(), nullable=True),
    sa.Column('Uglovaya', sa.Boolean(), nullable=True),
    sa.Column('StoronySveta', sa.String(), nullable=True),
    sa.Column('Vidovaya', sa.Boolean(), nullable=True),
    sa.Column('Cost', sa.BIGINT(), nullable=True),
    sa.Column('Area', sa.Float(), nullable=True),
    sa.Column('PloshadVnutrenaya', sa.Float(), nullable=True),
    sa.Column('RoomsCount', sa.Integer(), nullable=True),
    sa.Column('KolichestvoStoron', sa.String(), nullable=True),
    sa.Column('SkidkaProcent', sa.Float(), nullable=True),
    sa.Column('SkidkaNachalnikaOPProcent', sa.Float(), nullable=True),
    sa.Column('Natsenka', sa.Integer(), nullable=True),
    sa.Column('Podezd', sa.Integer(), nullable=True),
    sa.Column('Class_', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('AgreementDate', sa.DateTime(), nullable=True),
    sa.Column('SalePrice', sa.BIGINT(), nullable=True),
    sa.Column('Summa', sa.BIGINT(), nullable=True),
    sa.Column('ProcentVznosa', sa.Integer(), nullable=True),
    sa.Column('Aktsiya', sa.String(), nullable=True),
    sa.Column('AktsiyaGUID', sa.UUID(), nullable=True),
    sa.Column('DateOfSalesStart', sa.DateTime(), nullable=True),
    sa.Column('PloshadVnutrenayaPoTP', sa.Float(), nullable=True),
    sa.Column('PloshadBalkonaPoTP', sa.Float(), nullable=True),
    sa.Column('ZhilayaPloshadPoTP', sa.Float(), nullable=True),
    sa.Column('StartovayaTsena', sa.BIGINT(), nullable=True),
    sa.Column('Kod', sa.String(), nullable=True),
    sa.Column('Divizion', sa.String(), nullable=True),
    sa.Column('DataDogovora', sa.DateTime(), nullable=True),
    sa.Column('Mestonahozhdenie', sa.String(), nullable=True),
    sa.Column('TipRassrochki', sa.String(), nullable=True),
    sa.Column('ObjectNaimeovanie', sa.String(), nullable=True),
    sa.Column('DivizionNaimeovanie', sa.String(), nullable=True),
    sa.Column('Dolgota', sa.Float(), nullable=True),
    sa.Column('Shirota', sa.Float(), nullable=True),
    sa.Column('StaroeNaimeovanie', sa.String(), nullable=True),
    sa.Column('NovoeNaimeovanie', sa.String(), nullable=True),
    sa.Column('Investitsionnaya', sa.Boolean(), nullable=True),
    sa.Column('ChistovayaOtdelka', sa.Boolean(), nullable=True),
    sa.Column('TipChistovoyOtdelki', sa.String(), nullable=True),
    sa.Column('TipPlanirovki', sa.String(), nullable=True),
    sa.Column('Orientatsiya', sa.String(), nullable=True),
    sa.Column('Likvidnost', sa.String(), nullable=True),
    sa.Column('PloshadBalkona', sa.Float(), nullable=True),
    sa.Column('ZhilayaPloshad', sa.Integer(), nullable=True),
    sa.Column('VysotaPotolkovKvartira', sa.String(), nullable=True),
    sa.Column('Moshchnost', sa.String(), nullable=True),
    sa.Column('Prodano', sa.Integer(), nullable=True),
    sa.Column('Svetovaya', sa.Boolean(), nullable=True),
    sa.Column('DataZayavki', sa.DateTime(), nullable=True),
    sa.Column('VariantIspolneniya', sa.String(), nullable=True),
    sa.Column('PrizhataKUglu', sa.Boolean(), nullable=True),
    sa.Column('StoronaSvetaMaks', sa.String(), nullable=True),
    sa.Column('StoronaSvetaMin', sa.String(), nullable=True),
    sa.Column('LodgiyaNaKuhne', sa.Boolean(), nullable=True),
    sa.Column('SovmeshchennyySanuzel', sa.Boolean(), nullable=True),
    sa.Column('KolichestvoSanuzlov', sa.Integer(), nullable=True),
    sa.Column('DataDSPoAktu', sa.DateTime(), nullable=True),
    sa.Column('DataDkp', sa.DateTime(), nullable=True),
    sa.Column('DataDp', sa.DateTime(), nullable=True),
    sa.Column('Studiya', sa.Boolean(), nullable=True),
    sa.Column('Type_', sa.String(), nullable=True),
    sa.Column('ToSale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('PomeshcheniyeGUID')
    )
    op.create_table('dopolnitelnye_rekvizity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssylka', sa.String(), nullable=True),
    sa.Column('nomerStroki', sa.Integer(), nullable=True),
    sa.Column('svoistvo', sa.String(), nullable=True),
    sa.Column('znachenie', sa.String(), nullable=True),
    sa.Column('textovoePole', sa.String(), nullable=True),
    sa.Column('PomeshcheniyeGUID', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['PomeshcheniyeGUID'], ['pomeshcheniye_full.PomeshcheniyeGUID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sebestoimost', sa.BIGINT(), nullable=True),
    sa.Column('Rentabelnost', sa.Integer(), nullable=True),
    sa.Column('StoimostPoFinModeli', sa.BIGINT(), nullable=True),
    sa.Column('MinStoimostPoDDU', sa.BIGINT(), nullable=True),
    sa.Column('PomeshcheniyeGUID', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['PomeshcheniyeGUID'], ['pomeshcheniye_full.PomeshcheniyeGUID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fo')
    op.drop_table('dopolnitelnye_rekvizity')
    op.drop_table('pomeshcheniye_full')
    op.drop_table('pomeshcheniye')
    op.drop_table('blocks')
    # ### end Alembic commands ###
